apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-api
  labels: {{- include "assessment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels: { app: assessment-api }
  template:
    metadata:
      labels: { app: assessment-api }
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.backend.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels: { app: assessment-api }
              topologyKey: kubernetes.io/hostname
      {{- end }}
      securityContext: { runAsNonRoot: true, runAsUser: 10001, runAsGroup: 10001, fsGroup: 10001 }
      containers:
        - name: api
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports: [{ name: http, containerPort: 8080 }]
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://{{ .Values.database.host }}:5432/{{ .Values.database.name }}"
            - name: DATABASE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DATABASE_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.database.existingSecret }}, key: {{ .Values.database.passwordKey }} } }
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
          resources: {{- toYaml .Values.resources.backend | nindent 12 }}
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
          startupProbe: { httpGet: { path: /actuator/health/readiness, port: http }, periodSeconds: 5, failureThreshold: 30 }
          readinessProbe: { httpGet: { path: /actuator/health/readiness, port: http } }
          livenessProbe: { httpGet: { path: /actuator/health/liveness, port: http } }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: { drop: ["ALL"] } }
      volumes: [{ name: tmp, emptyDir: {} }]
---
apiVersion: v1
kind: Service
metadata: { name: assessment-api }
spec:
  selector: { app: assessment-api }
  ports: [{ name: http, port: 8080, targetPort: http }]
